# LM Value mapping
value_map     : {1: 40, 2: 80, 3: 120, 4: 200}

# Saving variables: set to False for dummy run
save_patches  : True

# Overlap option
read_type      : 'random'  # Change to 'sequential' for increased effiency, 'random' for random calls
overlap_factor : 0.0  # Portion of patches that are allowed to overlap (0->1)

# Misc
white_color : 250
scale       : 16
patch_size  : !!python/tuple [256, 256]
num_workers : 1
num_patches : 10 # -1 to mine until exhaustion, or a + int for number of patches

# RGB Masking
pen_size_threshold   : 200
min_color_difference : 30
pen_mask_threshold   : 9

# HSV Masking
hsv_s_threshold : 15
hsv_v_threshold : 90
